name: "Update Pull Request"

on: pull_request

jobs:
  pr_update_text:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        branch-regex: 'foo-\d+'
        lowercase-branch: false
        title-template: '[%branch%]'
        replace-title: false
        title-prefix-space: true
        uppercase-title: true
        body-template: |
          '[Link to %branch%](https://url/to/browse/ticket/%branch%)'
          This will also get prefixed to the PR body
        replace-body: false
        body-prefix-newline-count: 2
        uppercase-body: true
