name: "Update Pull Request"
on: pull_request

jobs:
  update_pr:
    runs-on: ubuntu-latest
    outputs:
      baseMatch: ${{ steps.update_pr.outputs.baseMatch }}
      headMatch: ${{ steps.update_pr.outputs.headMatch }}
      titleUpdated: ${{ steps.update_pr.outputs.titleUpdated }}
      bodyUpdated: ${{ steps.update_pr.outputs.bodyUpdated }}
    steps:
    - id: update_pr
      uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: '[a-z\d-_.\\/]+'
        head-branch-regex: 'foo-\d+'
        title-template: '[%headbranch%] '
        body-template: |
          Merging into '%basebranch%'
          [Link to %headbranch%](https://url/to/browse/ticket/%headbranch%)
        body-update-action: 'suffix'
        body-uppercase-base-match: false
  check_outputs:
      runs-on: ubuntu-latest
      needs: update_pr
      steps:
      - run: |
          echo 'baseMatch:' ${{needs.update_pr.outputs.baseMatch}}
          echo 'headMatch:' ${{needs.update_pr.outputs.headMatch}}
          echo 'titleUpdated:' ${{needs.update_pr.outputs.titleUpdated}}
          echo 'bodyUpdated:' ${{needs.update_pr.outputs.bodyUpdated}}
