name: "Update Pull Request"

on: pull_request

jobs:
  pr_update_text:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        branch-regex: 'FOO-\d+'
        lowercase-branch: false
        title-template: '[%branch%] '
        uppercase-title: false
        body-template: '[Link to %branch%](https://url/to/browse/ticket/%branch%)\n\n'
        uppercase-body: false
